language: python
dist: bionic
sudo: required

python:
    - "3.7"

branches:
  only:
    - source
    - master

install:
  - pip install -r requirements.txt
  - sudo snap install tree

script:
  - bash publish.sh


