language: python
dist: bionic
sudo: required

python:
    - "3.8"

branches:
  only:
    - source
    - master

install:
  - python -m pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install ez_setup
  - pip install unroll
  - pip install -U git+https://github.com/drunkpig/mdwiki.git
  - sudo snap install tree

script:
  - mdpub

