language: python
dist: bionic
sudo: required

python:
    - "3.8"

branches:
  only:
    - source
    - master

install:
  - pip install --upgrade pip
  - pip install setuptools
  - pip install -U git+https://github.com/drunkpig/mdwiki.git
  - sudo snap install tree

script:
  - mdpub

