# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: github-page-deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  setupenv:
    name: setup-env
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: insall python
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -U git+https://github.com/drunkpig/mdwiki.git
          sudo snap install tree
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: get code AT master branch
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - run: |
          pwd
          # ls -ltR /home/runner/work/drunkpig.github.io/drunkpig.github.io
          rm -rf 2*
          rm -rf css
          rm -rf image
          rm -rf js
          rm -rf *.html
          mdwiki_exec ./post   ./
          echo "准备提交的编译结果如下："
          ls -ltR /home/runner/work/drunkpig.github.io/drunkpig.github.io
    
      - name: deploy
        env:
          MY_EMAIL: kernel.h@gmail.com
          MY_NAME: drunkpig
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
          git remote set-url origin https://$MY_NAME:${{ secrets.GH_SECRET }}@github.com/drunkpig/drunkpig.github.io
          git push origin master


